// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: add.proto

package my_game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actions int32

const (
	Actions_KILL    Actions = 0
	Actions_CHECK   Actions = 1
	Actions_NOTHING Actions = 2
)

// Enum value maps for Actions.
var (
	Actions_name = map[int32]string{
		0: "KILL",
		1: "CHECK",
		2: "NOTHING",
	}
	Actions_value = map[string]int32{
		"KILL":    0,
		"CHECK":   1,
		"NOTHING": 2,
	}
)

func (x Actions) Enum() *Actions {
	p := new(Actions)
	*p = x
	return p
}

func (x Actions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Actions) Descriptor() protoreflect.EnumDescriptor {
	return file_add_proto_enumTypes[0].Descriptor()
}

func (Actions) Type() protoreflect.EnumType {
	return &file_add_proto_enumTypes[0]
}

func (x Actions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Actions.Descriptor instead.
func (Actions) EnumDescriptor() ([]byte, []int) {
	return file_add_proto_rawDescGZIP(), []int{0}
}

type Role int32

const (
	Role_CIVILIAN Role = 0
	Role_MAFIA    Role = 1
	Role_COMISSAR Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "CIVILIAN",
		1: "MAFIA",
		2: "COMISSAR",
	}
	Role_value = map[string]int32{
		"CIVILIAN": 0,
		"MAFIA":    1,
		"COMISSAR": 2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_add_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_add_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_add_proto_rawDescGZIP(), []int{1}
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role     Role   `protobuf:"varint,2,opt,name=role,proto3,enum=mafia.Role" json:"role,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_add_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_add_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_CIVILIAN
}

type Victim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	SessionId int32  `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *Victim) Reset() {
	*x = Victim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Victim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Victim) ProtoMessage() {}

func (x *Victim) ProtoReflect() protoreflect.Message {
	mi := &file_add_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Victim.ProtoReflect.Descriptor instead.
func (*Victim) Descriptor() ([]byte, []int) {
	return file_add_proto_rawDescGZIP(), []int{1}
}

func (x *Victim) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Victim) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role      Role   `protobuf:"varint,2,opt,name=role,proto3,enum=mafia.Role" json:"role,omitempty"`
	SessionId int32  `protobuf:"varint,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_add_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_add_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_CIVILIAN
}

func (x *User) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to EventVariant:
	//
	//	*Event_Booked
	//	*Event_NewGame
	//	*Event_NightIsComming
	//	*Event_MorningIsComing
	//	*Event_DiedName
	//	*Event_Result
	EventVariant isEvent_EventVariant `protobuf_oneof:"EventVariant"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_add_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_add_proto_rawDescGZIP(), []int{3}
}

func (m *Event) GetEventVariant() isEvent_EventVariant {
	if m != nil {
		return m.EventVariant
	}
	return nil
}

func (x *Event) GetBooked() *Empty {
	if x, ok := x.GetEventVariant().(*Event_Booked); ok {
		return x.Booked
	}
	return nil
}

func (x *Event) GetNewGame() *User {
	if x, ok := x.GetEventVariant().(*Event_NewGame); ok {
		return x.NewGame
	}
	return nil
}

func (x *Event) GetNightIsComming() *Night {
	if x, ok := x.GetEventVariant().(*Event_NightIsComming); ok {
		return x.NightIsComming
	}
	return nil
}

func (x *Event) GetMorningIsComing() *Morning {
	if x, ok := x.GetEventVariant().(*Event_MorningIsComing); ok {
		return x.MorningIsComing
	}
	return nil
}

func (x *Event) GetDiedName() string {
	if x, ok := x.GetEventVariant().(*Event_DiedName); ok {
		return x.DiedName
	}
	return ""
}

func (x *Event) GetResult() string {
	if x, ok := x.GetEventVariant().(*Event_Result); ok {
		return x.Result
	}
	return ""
}

type isEvent_EventVariant interface {
	isEvent_EventVariant()
}

type Event_Booked struct {
	Booked *Empty `protobuf:"bytes,1,opt,name=booked,proto3,oneof"`
}

type Event_NewGame struct {
	NewGame *User `protobuf:"bytes,2,opt,name=newGame,proto3,oneof"`
}

type Event_NightIsComming struct {
	NightIsComming *Night `protobuf:"bytes,3,opt,name=nightIsComming,proto3,oneof"`
}

type Event_MorningIsComing struct {
	MorningIsComing *Morning `protobuf:"bytes,4,opt,name=morningIsComing,proto3,oneof"`
}

type Event_DiedName struct {
	DiedName string `protobuf:"bytes,5,opt,name=diedName,proto3,oneof"`
}

type Event_Result struct {
	Result string `protobuf:"bytes,6,opt,name=result,proto3,oneof"`
}

func (*Event_Booked) isEvent_EventVariant() {}

func (*Event_NewGame) isEvent_EventVariant() {}

func (*Event_NightIsComming) isEvent_EventVariant() {}

func (*Event_MorningIsComing) isEvent_EventVariant() {}

func (*Event_DiedName) isEvent_EventVariant() {}

func (*Event_Result) isEvent_EventVariant() {}

type Night struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListOfPeople string  `protobuf:"bytes,1,opt,name=listOfPeople,proto3" json:"listOfPeople,omitempty"`
	Action       Actions `protobuf:"varint,2,opt,name=action,proto3,enum=mafia.Actions" json:"action,omitempty"`
}

func (x *Night) Reset() {
	*x = Night{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Night) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Night) ProtoMessage() {}

func (x *Night) ProtoReflect() protoreflect.Message {
	mi := &file_add_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Night.ProtoReflect.Descriptor instead.
func (*Night) Descriptor() ([]byte, []int) {
	return file_add_proto_rawDescGZIP(), []int{4}
}

func (x *Night) GetListOfPeople() string {
	if x != nil {
		return x.ListOfPeople
	}
	return ""
}

func (x *Night) GetAction() Actions {
	if x != nil {
		return x.Action
	}
	return Actions_KILL
}

type Morning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListOfPeople string `protobuf:"bytes,1,opt,name=listOfPeople,proto3" json:"listOfPeople,omitempty"`
	Announce     string `protobuf:"bytes,2,opt,name=announce,proto3" json:"announce,omitempty"`
	Alive        bool   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
}

func (x *Morning) Reset() {
	*x = Morning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Morning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Morning) ProtoMessage() {}

func (x *Morning) ProtoReflect() protoreflect.Message {
	mi := &file_add_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Morning.ProtoReflect.Descriptor instead.
func (*Morning) Descriptor() ([]byte, []int) {
	return file_add_proto_rawDescGZIP(), []int{5}
}

func (x *Morning) GetListOfPeople() string {
	if x != nil {
		return x.ListOfPeople
	}
	return ""
}

func (x *Morning) GetAnnounce() string {
	if x != nil {
		return x.Announce
	}
	return ""
}

func (x *Morning) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_add_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_add_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_add_proto_rawDescGZIP(), []int{6}
}

var File_add_proto protoreflect.FileDescriptor

var file_add_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x64, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x22, 0x47, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x42, 0x0a, 0x06, 0x56,
	0x69, 0x63, 0x74, 0x69, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x61, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x94, 0x02, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06,
	0x62, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d,
	0x61, 0x66, 0x69, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x06, 0x62, 0x6f,
	0x6f, 0x6b, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a,
	0x0e, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x49, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x4e, 0x69,
	0x67, 0x68, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x49, 0x73, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x3a, 0x0a, 0x0f, 0x6d, 0x6f, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x49, 0x73, 0x43, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x4d, 0x6f, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x00,
	0x52, 0x0f, 0x6d, 0x6f, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x73, 0x43, 0x6f, 0x6d, 0x69, 0x6e,
	0x67, 0x12, 0x1c, 0x0a, 0x08, 0x64, 0x69, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x64, 0x69, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x22, 0x53, 0x0a, 0x05, 0x4e, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x50, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66,
	0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5f,
	0x0a, 0x07, 0x4d, 0x6f, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x69, 0x73,
	0x74, 0x4f, 0x66, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69,
	0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x2b, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x49, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x54, 0x48,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x2a, 0x2d, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0c, 0x0a,
	0x08, 0x43, 0x49, 0x56, 0x49, 0x4c, 0x49, 0x41, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4d,
	0x41, 0x46, 0x49, 0x41, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x49, 0x53, 0x53,
	0x41, 0x52, 0x10, 0x02, 0x32, 0x64, 0x0a, 0x05, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x12, 0x2a, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0c, 0x2e, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2f, 0x0a, 0x0e, 0x56, 0x6f, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x0d, 0x2e, 0x6d, 0x61,
	0x66, 0x69, 0x61, 0x2e, 0x56, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x1a, 0x0c, 0x2e, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f,
	0x6d, 0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_add_proto_rawDescOnce sync.Once
	file_add_proto_rawDescData = file_add_proto_rawDesc
)

func file_add_proto_rawDescGZIP() []byte {
	file_add_proto_rawDescOnce.Do(func() {
		file_add_proto_rawDescData = protoimpl.X.CompressGZIP(file_add_proto_rawDescData)
	})
	return file_add_proto_rawDescData
}

var file_add_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_add_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_add_proto_goTypes = []interface{}{
	(Actions)(0),     // 0: mafia.Actions
	(Role)(0),        // 1: mafia.Role
	(*UserInfo)(nil), // 2: mafia.UserInfo
	(*Victim)(nil),   // 3: mafia.Victim
	(*User)(nil),     // 4: mafia.User
	(*Event)(nil),    // 5: mafia.Event
	(*Night)(nil),    // 6: mafia.Night
	(*Morning)(nil),  // 7: mafia.Morning
	(*Empty)(nil),    // 8: mafia.Empty
}
var file_add_proto_depIdxs = []int32{
	1, // 0: mafia.UserInfo.role:type_name -> mafia.Role
	1, // 1: mafia.User.role:type_name -> mafia.Role
	8, // 2: mafia.Event.booked:type_name -> mafia.Empty
	4, // 3: mafia.Event.newGame:type_name -> mafia.User
	6, // 4: mafia.Event.nightIsComming:type_name -> mafia.Night
	7, // 5: mafia.Event.morningIsComing:type_name -> mafia.Morning
	0, // 6: mafia.Night.action:type_name -> mafia.Actions
	2, // 7: mafia.Mafia.Start:input_type -> mafia.UserInfo
	3, // 8: mafia.Mafia.VoteProcessing:input_type -> mafia.Victim
	5, // 9: mafia.Mafia.Start:output_type -> mafia.Event
	8, // 10: mafia.Mafia.VoteProcessing:output_type -> mafia.Empty
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_add_proto_init() }
func file_add_proto_init() {
	if File_add_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_add_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Victim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Night); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Morning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_add_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_add_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Event_Booked)(nil),
		(*Event_NewGame)(nil),
		(*Event_NightIsComming)(nil),
		(*Event_MorningIsComing)(nil),
		(*Event_DiedName)(nil),
		(*Event_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_add_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_add_proto_goTypes,
		DependencyIndexes: file_add_proto_depIdxs,
		EnumInfos:         file_add_proto_enumTypes,
		MessageInfos:      file_add_proto_msgTypes,
	}.Build()
	File_add_proto = out.File
	file_add_proto_rawDesc = nil
	file_add_proto_goTypes = nil
	file_add_proto_depIdxs = nil
}
